# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalitemtype',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventorysystem.Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventorysystem.Department'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventorysystem.Department'),
        ),
    ]
