# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20170114_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemtype',
            name='product_classification',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalitemtype',
            name='product_type',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='batch_code',
            field=models.CharField(default=b'01-17', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='re_pr',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shelf',
            field=models.CharField(editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='product_classification',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='product_type',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
